### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [danwright32/prj-rev-bwfs-dasmoto#4]
Notice how you have to keep setting font-family for many of the selectors. It would be easier to just set it in one place, in this case we can use inheritance.
html { font-family: Helvetica; } 
Now all elements will inherit this font from html.

https://github.com/danwright32/prj-rev-bwfs-dasmoto/blob/master/Arts%20and%20Crafts/Resources/CSS/index.css#L14

**Comment by danwright32** [comment]
Awesome! I knew there had to be a way to do this. Thank you.
